export const friendListMock = [
  {
    id: 1,
    img: 'https://reqres.in/img/faces/7-image.jpg',
    first_name: 'Jeremy',
    last_name: 'Davis',
    status: 'At work...',
    available: false,
  },
  {
    id: 2,
    img: 'https://reqres.in/img/faces/8-image.jpg',
    first_name: 'Vlad',
    last_name: 'Baratovich',
    status: 'Hangout out by the pool',
    available: true,
  },
  {
    id: 3,
    img: 'https://reqres.in/img/faces/9-image.jpg',
    first_name: 'Reese',
    last_name: 'Samsonite',
    status: 'At NG-conf!',
    available: true,
  },
  {
    id: 4,
    img: 'https://reqres.in/img/faces/10-image.jpg',
    first_name: 'Edwardo',
    last_name: 'Gonzalez',
    status: 'Developing something amazing',
    available: false,
  },
  {
    id: 5,
    img: 'https://reqres.in/img/faces/11-image.jpg',
    first_name: 'Jim',
    last_name: 'Denison',
    status: 'Designing beatiful things',
    available: false,
  },
  {
    id: 6,
    img: 'https://reqres.in/img/faces/12-image.jpg',
    first_name: 'Steph',
    last_name: 'Walters',
    status: 'Developing something amazing',
    available: true,
  },
];
